### ISSUE TITLE
node 0.12 install fails

### ISSUE THREAD

**Issue by valorkin** [ludohenin/angular2-seed-ng2-bootstrap#1]
node 0.12
path=tools/tasks file=build.csslib.dev.ts

`file.endsWith('.ts')` endsWith is not a function

``` bash
[18:00:06] Requiring external module ts-node/register
/home/valorkin/work/open-source/angular2-seed-ng2-bootstrap/tools/utils/tasks-tools.ts:32
    readdirSync(path).forEach(function(file) {
                      ^
TypeError: undefined is not a function
    at /home/valorkin/work/open-source/angular2-seed-ng2-bootstrap/tools/utils/tasks-tools.ts:41:47
    at Array.forEach (native)
    at walk (/home/valorkin/work/open-source/angular2-seed-ng2-bootstrap/tools/utils/tasks-tools.ts:32:23)
    at scanDir (/home/valorkin/work/open-source/angular2-seed-ng2-bootstrap/tools/utils/tasks-tools.ts:29:3)
    at Object.autoRegisterTasks (/home/valorkin/work/open-source/angular2-seed-ng2-bootstrap/tools/utils/tasks-tools.ts:10:3)
    at Object.<anonymous> (/home/valorkin/work/open-source/angular2-seed-ng2-bootstrap/gulpfile.ts:13:1)
    at Module._compile (module.js:460:26)
    at Object.loader (/home/valorkin/work/open-source/angular2-seed-ng2-bootstrap/node_modules/ts-node/dist/ts-node.js:94:18)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

**Comment by valorkin** [comment]
I suppose in node 4 it will work

**Comment by ludohenin** [comment]
yes, this is a known issue (see parent repo - angular2-seed)
